---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-build-inventory
spec:
  params:
    - name: icd-source-repository
      description: the ICD source repository
    - name: icd-source-repository-branch
      description: the branch for the git repo
    - name: target-inventory-repository
      description: the target repository where inventory files will be stored
    - name: target-inventory-repository-branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: git-access-token
      description: illustrate alternate way to provide/get git access token
      default: ""
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-build-inventory
        params:
          - name: icd-source-repository
            value: $(params.icd-source-repository)
          - name: icd-source-repository-branch
            value: $(params.icd-source-repository-branch)
          - name: target-inventory-repository
            value: $(params.target-inventory-repository)
          - name: target-inventory-repository-branch
            value: $(params.target-inventory-repository-branch)
          - name: git-access-token
            value: $(params.git-access-token)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-build-inventory
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-build-inventory
spec:
  triggers:
    - binding:
        name: trigger-binding-build-inventory
      template:
        name: trigger-template-build-inventory