---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-build-inventory
spec:
  params:
    - name: icd-source-repository
      description: the ICD source repository
    - name: icd-source-repository-branch
      description: the branch for the git repo
    - name: icd-source-repository-directory
      description: name of the new directory to clone into
    - name: icd-component-name
      description: the name of the ICD component (database, control-plane, ...)
    - name: icd-configuration-file
      description: the configuration file containing the deployment information
    - name: target-inventory-repository
      description: the target repository where inventory files will be stored
    - name: target-inventory-repository-branch
      description: the branch for the git repo
    - name: target-inventory-repository-directory
      description: name of the new directory to clone into
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: build-inventory-$(uid)
      spec:
        pipelineRef:
          name: pipeline-build-inventory
        params:
          - name: icd-source-repository
            value: $(params.icd-source-repository)
          - name: icd-source-repository-branch
            value: $(params.icd-source-repository-branch)
          - name: icd-source-repository-directory
            value: $(params.icd-source-repository-directory)
          - name: icd-component-name
            value: $(params.icd-component-name)
          - name: icd-configuration-file
            value: $(params.icd-configuration-file)
          - name: target-inventory-repository
            value: $(params.target-inventory-repository)
          - name: target-inventory-repository-branch
            value: $(params.target-inventory-repository-branch)
          - name: target-inventory-repository-directory
            value: $(params.target-inventory-repository-directory)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-build-inventory
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-build-inventory-defaults
spec:
  triggers:
    - binding:
        name: trigger-binding-build-inventory
      template:
        name: trigger-template-build-inventory
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-build-inventory-icd-orchestration
spec:
  params:
    - name: icd-component-name
      value: 'icd-orchestration'
    - name: icd-configuration-file
      value: 'image_values.yaml'
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-build-inventory-icd-orchestration
spec:
  triggers:
    - binding:
        name: trigger-binding-build-inventory-icd-orchestration
      template:
        name: trigger-template-build-inventory
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-build-inventory-icd-control-plane
spec:
  params:
    - name: icd-component-name
      value: 'icd-control-plane'
    - name: icd-configuration-file
      value: 'values.yaml'
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-build-inventory-icd-control-plane
spec:
  triggers:
    - binding:
        name: trigger-binding-build-inventory-icd-control-plane
      template:
        name: trigger-template-build-inventory