---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-build-inventory
spec:
  params:
    - name: image-pull-policy
      default: Always
    - name: image-version
      default: latest
  resourcetemplates:
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: build-inventory-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: build-inventory-$(uid)
      spec:
        pipelineRef:
          name: pipeline-build-inventory
        params:
          - name: image-pull-policy
            value: $(params.image-pull-policy)
          - name: image-version
            value: $(params.image-version)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: build-inventory-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-build-inventory
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-build-inventory
spec:
  triggers:
    - binding:
        name: trigger-binding-build-inventory
      template:
        name: trigger-template-build-inventory
