---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-do-nothing
spec:
  params:
    - name: image-pull-policy
    - name: image-version
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: do-nothing
      taskRef:
        name: do-nothing
      params:
        - name: image-pull-policy
          value: $(params.image-pull-policy)
        - name: image-version
          value: $(params.image-version)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
