---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-inventory
spec:
  params:
    - name: icd-source-repository
      description: the ICD source repository
    - name: icd-source-repository-branch
      description: the branch for the git repo
    - name: icd-source-repository-directory
      description: name of the new directory to clone into
    - name: target-inventory-repository
      description: the target repository where inventory files will be stored
    - name: target-inventory-repository-branch
      description: the branch for the git repo
    - name: target-inventory-repository-directory
      description: name of the new directory to clone into
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-icd-source-repository
      taskRef:
        name: git-clone-repo
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.icd-source-repository)
        - name: branch
          value: $(params.icd-source-repository-branch)
        - name: directory-name
          value: $(params.icd-source-repository-directory)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: clone-target-inventory-repository
      taskRef:
        name: git-clone-repo
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.target-inventory-repository)
        - name: branch
          value: $(params.target-inventory-repository-branch)
        - name: directory-name
          value: $(params.target-inventory-repository-directory)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: icd-orchestration
      taskRef:
        name: build-inventory-icd-orchestration
      runAfter:
        - clone-icd-source-repository
        - clone-target-inventory-repository
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: icd-source-repository-directory
          value: $(params.icd-source-repository-directory)
        - name: target-inventory-repository-directory
          value: $(params.target-inventory-repository-directory)
        - name: repository
          value: $(params.icd-source-repository)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: control-plane
      taskRef:
        name: build-inventory-control-plane
      runAfter:
        - clone-icd-source-repository
        - clone-target-inventory-repository
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: icd-source-repository-directory
          value: $(params.icd-source-repository-directory)
        - name: target-inventory-repository-directory
          value: $(params.target-inventory-repository-directory)
        - name: repository
          value: $(params.icd-source-repository)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: commit-changes
      taskRef:
        name: commit-changes
      runAfter:
        - icd-orchestration
        - control-plane
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: target-inventory-repository-directory
          value: $(params.target-inventory-repository-directory)
        - name: pipeline-debug
          value: $(params.pipeline-debug)