---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-inventory
spec:
  params:
    - name: icd-source-repository
      description: the ICD source repository
      default: https://github.ibm.com/ibm-cloud-databases/ibm-cloud-databases
    - name: icd-source-repository-branch
      description: the branch for the git repo
    - name: target-inventory-repository
      description: the target repository where inventory files will be stored
    - name: target-inventory-repository-branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key 
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-icd-source-repository
      taskRef:
        name: git-clone-repo
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.icd-source-repository)
        - name: branch
          value: $(params.icd-source-repository-branch)
        - name: apikey
          value: $(params.apikey)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: clone-target-inventory-repository
      taskRef:
        name: git-clone-repo
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.target-inventory-repository)
        - name: branch
          value: $(params.target-inventory-repository-branch)
        - name: apikey
          value: $(params.apikey)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: build-inventory
      taskRef:
        name: build-inventory
      workspaces:
        - name: output
          workspace: pipeline-ws
      params:
        - name: icd-source-repository
          value: $(params.icd-source-repository)
        - name: target-inventory-repository
          value: $(params.target-inventory-repository)