---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-do-nothing
spec:
  params:
  resourcetemplates:
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: do-nothing-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: do-nothing-$(uid)
      spec:
        pipelineRef:
          name: pipeline-do-nothing
        params:
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: do-nothing-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-do-nothing
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-do-nothing
spec:
  triggers:
    - binding:
        name: trigger-binding-do-nothing
      template:
        name: trigger-template-do-nothing
