---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-do-nothing
spec:
  params:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: do-nothing
      taskRef:
        name: do-nothing
      params:
      workspaces:
        - name: workspace
          workspace: pipeline-ws
