---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: do-nothing
spec:
  params:
  workspaces:
    - name: workspace
      description: |
        A workspace that contain data useful for the script/slack message resolution.
        Should be marked as optional when Tekton will permit it
      mountPath: /artifacts
  steps:
    - name: fetch-base-image
      image: ibmcom/pipeline-base-image:2.6
      imagePullPolicy: "Always"
      script: |
        #!/bin/bash
        set -e -o pipefail
        exit 0