---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: do-nothing
spec:
  params:
    - name: image-pull-policy
      description: |
        the imagePullPolicy to use 
      default: "Always"
    - name: image-version
      description: |
        the image version to use 
      default: latest
  workspaces:
    - name: workspace
      description: |
        A workspace that contain data useful for the script/slack message resolution.
        Should be marked as optional when Tekton will permit it
      mountPath: /artifacts
  steps:
    - name: fetch-base-image
      image: ibmcom/pipeline-base-image:$(params.image-version)
      imagePullPolicy: "$(params.image-pull-policy)"
      env:
        - name: PULL_POLICY
          value: $(params.image-pull-policy)
        - name: IMAGE_VERSION
          value: $(params.image-version)
      script: |
        #!/bin/bash
        set -e -o pipefail
        echo  "imagePullPolicy: $PULL_POLICY - Image version: $IMAGE_VERSION"
        exit 0