---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-break-glass
spec:
  params:
    - name: api-key
    - name: pipeline-id
    - name: file-name
    - name: artifactory-repository
    - name: artifactory-api-key
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: break-glass
      taskRef:
        name: break-glass
      params:
        - name: api-key
          value: $(params.api-key)
        - name: pipeline-id
          value: $(params.pipeline-id)
        - name: file-name
          value: $(params.file-name)
        - name: artifactory-repository
          value: $(params.artifactory-repository)
        - name: artifactory-api-key
          value: $(params.artifactory-api-key)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
